### ISSUE TITLE
`impl futures::Stream for Page`

### ISSUE THREAD

**Issue by XAMPPRocky** [XAMPPRocky/octocrab#214]
Currently paging can be a bit awkward, it would be nice if we could implement a stream API for pages.

**Comment by XAMPPRocky** [comment]
@mbirtwell The addition would certainly be welcome, also that code seems pretty easily adaptable into being implemented on `Page`, it seems like it only requires adding `Octocrab` as field to Page, which seems reasonable to me if it provides the trait implementation.

**Comment by mbirtwell** [comment]
I think that we do need to track more state than is currently present on `Page`. Specifically we need to track where within the page we are. I do that in the example above by converting the `Page`'s `items` field in to a `std::vec::IntoIter` so that the iterator can track this for me implicitly. So I think that a separate struct for the stream will be nicer. 

One of the problems with my approach is that by using `try_unfold` to implement the stream it means that the stream is an existential type. Which will make it harder for people store it if they need to. It's also `!Unpin` it might be possible or organise the closure in a way that's `Unpin` but that seems awkward. So an explicit `Stream` impl on a new struct seems better. 

I still think constructing the new struct with a `into_stream` method on `Page` which takes a `&Octocrab` seems like the easiest thing to implement. I think using the library I'd expect to see a `stream` method as a sibling to the `send` method, but that could be implemented just by chaining `send` and `into_stream`.

**Comment by XAMPPRocky** [comment]
Fair enough, seems reasonable to me.

> I think using the library I'd expect to see a stream method as a sibling to the send method, but that could be implemented just by chaining send and into_stream.

Yeah, it would be nice if it was just `stream`, but that'd require an inherent method on every type that returns a page, so I think we should go with `into_stream` as a method on `Page`. Feel free to open a PR with the code.

> So an explicit Stream impl on a new struct seems better.

I'm fine with that, I'm also fine with just leaving it as an existential type for now, and then changing it later if someone requests it.

**Comment by mbirtwell** [comment]
Have you had a chance to look at #222? What did you think?
