### ISSUE TITLE
Enhance crate structure

### ISSUE THREAD

**Issue by kellda** [XAMPPRocky/octocrab#30]
The file `models.rs` is getting quite big, so I'd like to split it into smaller sub-modules.

What would be the best structure ? In thinking about
```
lib
├ issues
│ ├ api
│ ├ models
│ └ params
├ orgs
│ ├ api
│ ├ models
│ └ params
├ pulls
│ ├ api
│ ├ models
│ └ params
└ …
```
and
```
lib
├ api
│ ├ issues
│ ├ orgs
│ ├ pulls
│ └ …
├ models
│ ├ issues
│ ├ orgs
│ ├ pulls
│ └ …
└ params
  ├ issues
  ├ orgs
  ├ pulls
  └ …
```

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Splitting the models.rs in the same fashion makes sense. I would structure it like params where shared models are in the top level and modules are for models that aren't used elsewhere.

If you'd like to work on this, I would prefer if each area refactor (prs, issues, etc) was a separate PR for the sake of review rather than a single move.
