### ISSUE TITLE
missing fields in some structs?

### ISSUE THREAD

**Issue by classabbyamp** [XAMPPRocky/octocrab#419]
I'm using `octocrab`'s event models to parse webhook events and i've noticed some fields are missing. What's the best way to deal with this? Is there a way to access the rest of the fields? or maybe just make a PR adding the relevant fields?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Yes, PRs are always welcome and encouraged 🙂

**Comment by gagbo** [comment]
What did you have in mind? I'm currently adding deserialization for installation related webhook events

**Comment by classabbyamp** [comment]
for my purpose I at least need the `forced` field on `PushEvent`, maybe some other things I haven't spotted yet.

Maybe it would make sense to use [this serde feature](https://serde.rs/attr-flatten.html#capture-additional-fields) to allow extra fields to be accessed?

also, it might be nice to have a utility method on a `PushEvent` for accessing the `head` commit easily

(sorry for the grab-bag of suggestions, just what I've noticed might make some things easier)

**Comment by XAMPPRocky** [comment]
> Maybe it would make sense to use this serde feature to allow extra fields to be accessed?

It would be better to add the missing fields to the struct directly in a PR. We're not trying to handle an unknown number of fields, it's just that new fields get added, or people forget to add them when creating the definition, and that should be fixed directly. It would be unintuitive if some fields were put in a hash map and some were in the struct, they should just all be in the struct.

**Comment by XAMPPRocky** [comment]
Separate types seems like the correct approach.

**Comment by classabbyamp** [comment]
alright, I'm interested in working on this but I might not have time for a week or two.

**Comment by gagbo** [comment]
I think I'll spin something up by the end of the week, I really need this. The main issue is that Github doesn't answer [my question about the schema of webhook events](https://github.com/orgs/community/discussions/61453), and the documentation is quite lacking, so a lot of the payloads are just going to be `serde_json::Value` since the keys for objects are unknown. I'll try to implement properly the few events for which I have an actual payload coming from my test app
