### ISSUE TITLE
Newtypes for IDs

### ISSUE THREAD

**Issue by rocallahan** [XAMPPRocky/octocrab#84]
Seems to me it would be nice to have newtypes for the different IDs (orgs, users, check runs, workflow runs, etc). That would be an API break though. How do you feel about that?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Overall I'm supportive of the idea. At the very least it can make it easier to ensure all ids are using the correct type (it's currently inconsistent). In terms of implementation I think my preference would be for a macro_rules macro which creates the types for each of the structs, so that they can all share the same methods, while still being distinct types.

**Comment by rocallahan** [comment]
What methods do the newtypes need though? #[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)] and maybe Ord/PartialOrd is all I can think of.

**Comment by XAMPPRocky** [comment]
Well they'll need ways to extract and map the raw IDs, I don't think the type should be completely opaque, such as `into_inner` and `Deref`/`DerefMut` implementations, and `fmt::Display` implementations, as they should still print the numbers.

**Comment by rocallahan** [comment]
I would just make the inner number `pub`, but ok...

**Comment by rocallahan** [comment]
I see you've made ids be mostly `i64`. Do you know of any ids that can actually be negative?

**Comment by rocallahan** [comment]
Another question: what is `parse_u64` for? It doesn't do anything usefully different AFAICT

**Comment by XAMPPRocky** [comment]
If there was a reason, I have since forgot it, so feel free to disregard the current setup and make everything `u64` for now. If it turns out to be needed we can change that part later.
